services:
  sigma-web:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        NEXT_PUBLIC_API_URL: ${NEXT_PUBLIC_API_URL}
        NEXT_PUBLIC_SENTRY_DSN: ${NEXT_PUBLIC_SENTRY_DSN:-}
        SENTRY_AUTH_TOKEN: ${SENTRY_AUTH_TOKEN:-}
    image: sigma-web:latest
    container_name: sigma-web
    ports:
      - "3000:3000"
    restart: unless-stopped
    networks:
      - sigma-adonisjs_default

networks:
  sigma-adonisjs_default:
    external: true
